export function EmbedPreview({author,title,description,fields=[],footer,timestamp,color='var(--accent)',thumbnail,image,botName='Tobot',botTag='APP',style}){
  return React.createElement('div',{style:{display:'flex',gap:'var(--space-3)',padding:'var(--space-4)',
    background:'var(--bg-inset)',border:'1px solid var(--border-subtle)',borderRadius:'var(--radius-md)',...style}},
    React.createElement('span',{key:'av',style:{width:'34px',height:'34px',flexShrink:0,borderRadius:'var(--radius-pill)',
      background:'var(--accent)',color:'var(--on-accent)',display:'flex',alignItems:'center',justifyContent:'center',
      fontFamily:'var(--font-display)',fontWeight:800,fontSize:'16px'}},'t'),
    React.createElement('div',{key:'c',style:{flex:1,minWidth:0}},
      React.createElement('div',{key:'h',style:{display:'flex',alignItems:'center',gap:'6px'}},
        React.createElement('span',{style:{fontWeight:600,fontSize:'var(--text-body-s)',color:'var(--text-primary)'}},botName),
        React.createElement('span',{style:{padding:'1px 5px',borderRadius:'var(--radius-xs)',background:'var(--accent)',
          color:'var(--on-accent)',fontFamily:'var(--font-mono)',fontSize:'9px',fontWeight:700,letterSpacing:'.08em'}},botTag),
        timestamp?React.createElement('span',{style:{fontFamily:'var(--font-mono)',fontSize:'10px',color:'var(--text-muted)'}},timestamp):null),
      React.createElement('div',{key:'e',style:{marginTop:'6px',display:'flex',borderRadius:'var(--radius-sm)',
        background:'var(--bg-surface)',border:'1px solid var(--border-subtle)',overflow:'hidden'}},
        React.createElement('span',{key:'bar',style:{width:'4px',flexShrink:0,background:color}}),
        React.createElement('div',{key:'body',style:{flex:1,minWidth:0,padding:'var(--space-3) var(--space-4)'}},
          author?React.createElement('div',{key:'a',style:{fontSize:'var(--text-caption)',color:'var(--text-secondary)',marginBottom:'4px'}},author):null,
          title?React.createElement('div',{key:'t',style:{fontFamily:'var(--font-display)',fontWeight:700,fontSize:'var(--text-h4)',color:'var(--text-accent)'}},title):null,
          description?React.createElement('div',{key:'d',style:{marginTop:'4px',fontSize:'var(--text-body-s)',color:'var(--text-secondary)',lineHeight:1.55}},description):null,
          fields.length?React.createElement('div',{key:'f',style:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(120px,1fr))',gap:'var(--space-3)',marginTop:'var(--space-3)'}},
            fields.map((fl,i)=>React.createElement('div',{key:i},
              React.createElement('div',{style:{fontSize:'var(--text-caption)',fontWeight:600,color:'var(--text-primary)'}},fl.name),
              React.createElement('div',{style:{fontFamily:'var(--font-mono)',fontSize:'var(--text-mono-s)',color:'var(--text-secondary)'}},fl.value)))):null,
          image?React.createElement('div',{key:'im',style:{marginTop:'var(--space-3)',height:'88px',borderRadius:'var(--radius-xs)',
            background:'var(--bg-inset)',border:'1px dashed var(--border-default)',display:'flex',alignItems:'center',
            justifyContent:'center',fontFamily:'var(--font-mono)',fontSize:'10px',color:'var(--text-muted)'}},image):null,
          footer?React.createElement('div',{key:'ft',style:{marginTop:'var(--space-3)',fontFamily:'var(--font-mono)',fontSize:'10px',color:'var(--text-muted)'}},footer):null),
        thumbnail?React.createElement('div',{key:'th',style:{width:'56px',height:'56px',margin:'var(--space-3)',flexShrink:0,
          borderRadius:'var(--radius-xs)',background:'var(--bg-inset)',border:'1px dashed var(--border-default)'}}):null)));
}
